// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A travel journey generation AI agent.
 *
 * - generateTravelJourney - A function that handles the travel journey generation process.
 * - GenerateTravelJourneyInput - The input type for the generateTravelJourney function.
 * - GenerateTravelJourneyOutput - The return type for the generateTravelJourney function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTravelJourneyInputSchema = z.object({
  prompt: z.string().describe('A natural language prompt describing the desired trip.'),
  numberOfPeople: z.number().describe('The number of people in the travel party.'),
  arrivalDate: z.string().describe('The arrival date for the trip.'),
  dailyBudget: z.string().describe('The daily budget for the trip (select range or enter approximate average).'),
  vehicleAvailability: z.boolean().describe('Whether a vehicle is available for the trip.'),
  preferences: z.string().describe('The likes and dislikes of the travel party.'),
  detailLevel: z.number().describe('The desired schedule density for the journey (0: Light Outline, 1: Balanced Guide, 2: Detailed Plan, 3: Full Immersion).'),
});
export type GenerateTravelJourneyInput = z.infer<typeof GenerateTravelJourneyInputSchema>;

const GenerateTravelJourneyOutputSchema = z.object({
  journey: z.string().describe('A personalized travel journey with destinations, travel times, cost estimates, and dining options, tailored to the specified detail level.'),
});
export type GenerateTravelJourneyOutput = z.infer<typeof GenerateTravelJourneyOutputSchema>;

export async function generateTravelJourney(input: GenerateTravelJourneyInput): Promise<GenerateTravelJourneyOutput> {
  return generateTravelJourneyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTravelJourneyPrompt',
  input: {schema: GenerateTravelJourneyInputSchema},
  output: {schema: GenerateTravelJourneyOutputSchema},
  prompt: `You are an expert travel agent specializing in creating personalized travel journeys.

You will use the following information to generate a travel journey tailored to the user's needs and preferences.

Prompt: {{{prompt}}}
Number of People: {{{numberOfPeople}}}
Arrival Date: {{{arrivalDate}}}
Daily Budget: {{{dailyBudget}}}
Vehicle Availability: {{{vehicleAvailability}}}
Preferences: {{{preferences}}}
Schedule Density: {{{detailLevel}}} (Interpret 0 as a Light Outline with minimal guidance, 1 as a Balanced Guide with key activities and suggestions, 2 as a Detailed Plan with more structure, and 3 as a Full Immersion plan with hourly specifics for a packed day. Adjust the verbosity and specificity of the generated plan accordingly.)

Generate a detailed travel journey with destinations, travel times, cost estimates, and dining options. Ensure the output is a single string that can be directly displayed.`,  
});

const generateTravelJourneyFlow = ai.defineFlow(
  {
    name: 'generateTravelJourneyFlow',
    inputSchema: GenerateTravelJourneyInputSchema,
    outputSchema: GenerateTravelJourneyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!; 
  }
);

