// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A travel itinerary generation AI agent.
 *
 * - generateTravelItinerary - A function that handles the travel itinerary generation process.
 * - GenerateTravelItineraryInput - The input type for the generateTravelItinerary function.
 * - GenerateTravelItineraryOutput - The return type for the generateTravelItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTravelItineraryInputSchema = z.object({
  prompt: z.string().describe('A natural language prompt describing the desired trip.'),
  numberOfPeople: z.number().describe('The number of people in the travel party.'),
  arrivalDate: z.string().describe('The arrival date for the trip.'),
  dailyBudget: z.string().describe('The daily budget for the trip (select range or enter approximate average).'),
  vehicleAvailability: z.boolean().describe('Whether a vehicle is available for the trip.'),
  preferences: z.string().describe('The likes and dislikes of the travel party.'),
});
export type GenerateTravelItineraryInput = z.infer<typeof GenerateTravelItineraryInputSchema>;

const GenerateTravelItineraryOutputSchema = z.object({
  itinerary: z.string().describe('A personalized travel itinerary with destinations, travel times, cost estimates, and dining options.'),
});
export type GenerateTravelItineraryOutput = z.infer<typeof GenerateTravelItineraryOutputSchema>;

export async function generateTravelItinerary(input: GenerateTravelItineraryInput): Promise<GenerateTravelItineraryOutput> {
  return generateTravelItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTravelItineraryPrompt',
  input: {schema: GenerateTravelItineraryInputSchema},
  output: {schema: GenerateTravelItineraryOutputSchema},
  prompt: `You are an expert travel agent specializing in creating personalized travel itineraries.\n\nYou will use the following information to generate a travel itinerary tailored to the user's needs and preferences.\n\nPrompt: {{{prompt}}}\nNumber of People: {{{numberOfPeople}}}\nArrival Date: {{{arrivalDate}}}\nDaily Budget: {{{dailyBudget}}}\nVehicle Availability: {{{vehicleAvailability}}}\nPreferences: {{{preferences}}}\n\nGenerate a detailed travel itinerary with destinations, travel times, cost estimates, and dining options.`,  
});

const generateTravelItineraryFlow = ai.defineFlow(
  {
    name: 'generateTravelItineraryFlow',
    inputSchema: GenerateTravelItineraryInputSchema,
    outputSchema: GenerateTravelItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
