// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A travel journey generation AI agent.
 *
 * - generateTravelJourney - A function that handles the travel journey generation process.
 * - GenerateTravelJourneyInput - The input type for the generateTravelJourney function.
 * - GenerateTravelJourneyOutput - The return type for the generateTravelJourney function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTravelJourneyInputSchema = z.object({
  prompt: z.string().describe('A natural language prompt describing the desired trip.'),
  numberOfPeople: z.number().describe('The number of people in the travel party.'),
  arrivalDate: z.string().describe('The arrival date for the trip.'),
  dailyBudget: z.string().describe('The daily budget for the trip (select range or enter approximate average).'),
  vehicleAvailability: z.boolean().describe('Whether a vehicle is available for the trip.'),
  preferences: z.string().describe('The likes and dislikes of the travel party.'),
});
export type GenerateTravelJourneyInput = z.infer<typeof GenerateTravelJourneyInputSchema>;

const GenerateTravelJourneyOutputSchema = z.object({
  journey: z.string().describe('A personalized travel journey with destinations, travel times, cost estimates, and dining options.'),
});
export type GenerateTravelJourneyOutput = z.infer<typeof GenerateTravelJourneyOutputSchema>;

export async function generateTravelJourney(input: GenerateTravelJourneyInput): Promise<GenerateTravelJourneyOutput> {
  return generateTravelJourneyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTravelJourneyPrompt',
  input: {schema: GenerateTravelJourneyInputSchema},
  output: {schema: GenerateTravelJourneyOutputSchema},
  prompt: `You are an expert travel agent specializing in creating personalized travel journeys.\n\nYou will use the following information to generate a travel journey tailored to the user's needs and preferences.\n\nPrompt: {{{prompt}}}\nNumber of People: {{{numberOfPeople}}}\nArrival Date: {{{arrivalDate}}}\nDaily Budget: {{{dailyBudget}}}\nVehicle Availability: {{{vehicleAvailability}}}\nPreferences: {{{preferences}}}\n\nGenerate a detailed travel journey with destinations, travel times, cost estimates, and dining options.`,  
});

const generateTravelJourneyFlow = ai.defineFlow(
  {
    name: 'generateTravelJourneyFlow',
    inputSchema: GenerateTravelJourneyInputSchema,
    outputSchema: GenerateTravelJourneyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    // Assuming the output structure matches the schema, and 'journey' is the key.
    // If prompt output is directly the string, this might need adjustment.
    // For now, let's assume the prompt returns an object with a 'journey' field.
    // However, based on existing code, the prompt likely directly returns an object that fits GenerateTravelJourneyOutputSchema.
    // So, if prompt's output IS { journey: "..." }, then output!.journey is not needed, output! is fine.
    // The prompt definition output schema IS GenerateTravelJourneyOutputSchema, so output! should be { journey: "string" }.
    return output!; 
  }
);
